import { getDemoFixture } from "@/lib/config";
import {
  CAMPAIGN_WEEKEND_ID,
  FUNDER_ALTHEA_ID,
  FUNDER_ALTHEA_NAME,
  FUNDER_COMMUNITY_HEALTH_ID,
  FUNDER_COMMUNITY_HEALTH_NAME,
  FUNDER_COMMUNITY_ID,
  FUNDER_COMMUNITY_NAME,
  FUNDER_EMPLOYER_ID,
  FUNDER_EMPLOYER_NAME,
  COMMUNITY_PROGRAM_NAME,
  EMPLOYER_PROGRAM_NAME,
  GENERAL_PROGRAM_NAME,
  MATCH_PROGRAM_NAME,
  NETWORK_COMMUNITY_PROGRAM_ID,
  NETWORK_EMPLOYER_PROGRAM_ID,
  NETWORK_GENERAL_PROGRAM_ID,
  NETWORK_MATCH_PROGRAM_ID,
  NETWORK_RURAL_PROGRAM_ID,
  NETWORK_RULES_VERSION,
  RURAL_PROGRAM_NAME,
} from "@/lib/network/ids";
import type { StoredFunder, StoredMatchCampaign, StoredNetworkProgram } from "@/lib/network/types";

export function seedFunders(now: string): StoredFunder[] {
  return [
    {
      id: FUNDER_ALTHEA_ID,
      name: FUNDER_ALTHEA_NAME,
      kind: "althea",
      treasuryUsdc: getDemoFixture().demoAvailableCapital,
      dailyLimitUsdc: 5000,
      perMatchLimitUsdc: 250,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: FUNDER_COMMUNITY_HEALTH_ID,
      name: FUNDER_COMMUNITY_HEALTH_NAME,
      kind: "foundation",
      treasuryUsdc: 50_000,
      dailyLimitUsdc: 5000,
      perMatchLimitUsdc: 250,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: FUNDER_EMPLOYER_ID,
      name: FUNDER_EMPLOYER_NAME,
      kind: "employer",
      treasuryUsdc: 0,
      dailyLimitUsdc: 5000,
      perMatchLimitUsdc: 300,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: FUNDER_COMMUNITY_ID,
      name: FUNDER_COMMUNITY_NAME,
      kind: "community",
      treasuryUsdc: 8000,
      dailyLimitUsdc: 2000,
      perMatchLimitUsdc: 200,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function seedNetworkPrograms(now: string): StoredNetworkProgram[] {
  const demo = getDemoFixture();
  return [
    {
      id: NETWORK_GENERAL_PROGRAM_ID,
      funderId: FUNDER_ALTHEA_ID,
      name: GENERAL_PROGRAM_NAME,
      kind: "general",
      status: "active",
      currency: "USDC",
      budget: demo.demoAvailableCapital,
      spentAmount: 0,
      reservedAmount: 0,
      grantCap: 250,
      matchRatioNum: 0,
      matchRatioDen: 1,
      maxMatchPerCase: 0,
      ruleHash: NETWORK_RULES_VERSION,
      allowedRecipientMode: "verified_settlement_only",
      requiresWorldCheck: true,
      requiresFapCompletion: true,
      requiresVerifiedResidual: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: NETWORK_MATCH_PROGRAM_ID,
      funderId: FUNDER_COMMUNITY_HEALTH_ID,
      name: MATCH_PROGRAM_NAME,
      kind: "match",
      status: "active",
      currency: "USDC",
      budget: 2000,
      spentAmount: 0,
      reservedAmount: 0,
      grantCap: 250,
      matchRatioNum: 1,
      matchRatioDen: 1,
      maxMatchPerCase: 250,
      expiresAt: "2026-12-31T23:59:59.000Z",
      ruleHash: NETWORK_RULES_VERSION,
      eligibleSourceProgramId: NETWORK_GENERAL_PROGRAM_ID,
      allowedRecipientMode: "verified_settlement_only",
      requiresWorldCheck: true,
      requiresFapCompletion: true,
      requiresVerifiedResidual: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: NETWORK_EMPLOYER_PROGRAM_ID,
      funderId: FUNDER_EMPLOYER_ID,
      name: EMPLOYER_PROGRAM_NAME,
      kind: "employer",
      status: "paused",
      currency: "USDC",
      budget: 0,
      spentAmount: 0,
      reservedAmount: 0,
      grantCap: 300,
      matchRatioNum: 0,
      matchRatioDen: 1,
      maxMatchPerCase: 0,
      ruleHash: NETWORK_RULES_VERSION,
      allowedRecipientMode: "verified_settlement_only",
      requiresWorldCheck: true,
      requiresFapCompletion: true,
      requiresVerifiedResidual: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: NETWORK_COMMUNITY_PROGRAM_ID,
      funderId: FUNDER_COMMUNITY_ID,
      name: COMMUNITY_PROGRAM_NAME,
      kind: "community",
      status: "active",
      currency: "USDC",
      budget: 200,
      spentAmount: 0,
      reservedAmount: 0,
      grantCap: 200,
      matchRatioNum: 0,
      matchRatioDen: 1,
      maxMatchPerCase: 0,
      expiresAt: "2026-12-31T23:59:59.000Z",
      ruleHash: NETWORK_RULES_VERSION,
      allowedRecipientMode: "verified_settlement_only",
      requiresWorldCheck: true,
      requiresFapCompletion: true,
      requiresVerifiedResidual: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: NETWORK_RURAL_PROGRAM_ID,
      funderId: FUNDER_COMMUNITY_ID,
      name: RURAL_PROGRAM_NAME,
      kind: "community",
      status: "active",
      currency: "USDC",
      budget: 0,
      spentAmount: 0,
      reservedAmount: 0,
      grantCap: 250,
      matchRatioNum: 0,
      matchRatioDen: 1,
      maxMatchPerCase: 0,
      ruleHash: NETWORK_RULES_VERSION,
      allowedRecipientMode: "verified_settlement_only",
      requiresWorldCheck: true,
      requiresFapCompletion: true,
      requiresVerifiedResidual: true,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function seedCampaigns(): StoredMatchCampaign[] {
  return [
    {
      id: CAMPAIGN_WEEKEND_ID,
      programId: NETWORK_MATCH_PROGRAM_ID,
      name: "Double Every Dollar This Weekend",
      matchRatioNum: 1,
      matchRatioDen: 1,
      budget: 10_000,
      spent: 0,
      startsAt: "2026-09-12T00:00:00.000Z",
      endsAt: "2026-09-30T23:59:59.000Z",
      recipientProgramId: NETWORK_GENERAL_PROGRAM_ID,
      status: "active",
    },
  ];
}
